apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmms-backend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmms-backend
  template:
    metadata:
      labels:
        app: lmms-backend
    spec:
      containers:
        - name: backend
          image: missaouisyrine/lmms-back:0.5 #${LMMS_FRONT_REPO}:${IMAGE_TAG_BACKEND}
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: 8090 #"8090"
            - name: POSTGRES_DB
              value: lmms-database.production.svc.k8s.pfe #"lmms-database.production.svc.k8s.pfe"
            - name: DB_PORT
              value: 5432 #"5432"
            - name: DB_NAME
              value: TE1N #"LMM"
            - name: PS_USER_LMMS
              valueFrom:
                secretKeyRef:
                  name: lmms-backend-secrets
                  key: PS_USER_LMMS
            - name: PS_PASS_LMMS
              valueFrom:
                secretKeyRef:
                  name: lmms-backend-secrets
                  key: PS_PASS_LMMS