apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmms-frontend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmms-frontend
  template:
    metadata:
      labels:
        app: lmms-frontend
    spec:
      containers:
        - name: frontend
          image: missaouisyrine/lmms-front:1.3
          ports:
            - containerPort: 3000